services:
  cftun-ui:
    build: .
    image: cftun-ui:latest
    container_name: cftun-ui
    network_mode: host
    restart: unless-stopped
    stop_grace_period: 20s
    logging:
      driver: local
      options:
        max-size: "7m"
        max-file: "1"
        compress: "true"
    environment:
      SERVER_HOST: 0.0.0.0
      SERVER_PORT: 9911
      DATA_DIR: /data
    volumes:
      - cftun-data:/data

volumes:
  cftun-data:
    name: cftun-data
