<script setup lang="ts">
import { computed, nextTick, onBeforeUnmount, reactive, ref, watch } from "vue";
import { useScrollLock } from "../composables/useScrollLock";
import type { CloudflareChoice, Mapping, MappingInput, MappingTestResult, Operation } from "../types";
import SelectMenu from "./SelectMenu.vue";

const props = withDefaults(defineProps<{ open: boolean; mapping?: Mapping | null; zones: CloudflareChoice[]; defaultZoneId?: string; zonesLoading?: boolean; saving?: boolean; testing?: boolean; serverError?: string; testResult?: MappingTestResult | null; operation?: Operation | null; displayStage?: string }>(), { mapping: null, defaultZoneId: "", zonesLoading: false, saving: false, testing: false, serverError: "", testResult: null, operation: null, displayStage: "" });
const emit = defineEmits<{ close: []; save: [input: MappingInput]; test: [input: MappingInput] }>();
const panel = ref<HTMLElement | null>(null); const form = ref<HTMLFormElement | null>(null); const setLocked = useScrollLock(); const errors = reactive<Record<string, string>>({}); let previous: HTMLElement | null = null;
const draft = reactive({ zoneId: "", subdomain: "", path: "", targetType: "host" as "host"|"lan", protocol: "http" as "http"|"https", targetHost: "", targetPort: "", enabled: true, noTLSVerify: false });
const selectedZone = computed(() => props.zones.find((zone) => zone.id === draft.zoneId));
const zoneName = computed(() => selectedZone.value?.name || props.mapping?.zoneName || "");
const hostname = computed(() => !draft.subdomain || draft.subdomain === "@" ? zoneName.value : zoneName.value ? `${draft.subdomain}.${zoneName.value}` : "");
const zoneOptions = computed(() => props.zones.map((zone) => ({ value: zone.id, label: zone.name })));

function payload(): MappingInput { return { zoneId: draft.zoneId, zoneName: zoneName.value, hostname: hostname.value, path: draft.path.trim() || undefined, targetType: draft.targetType, protocol: draft.protocol, targetHost: draft.targetType === "lan" ? draft.targetHost.trim() : undefined, targetPort: Number(draft.targetPort), enabled: draft.enabled, noTLSVerify: draft.protocol === "https" && draft.noTLSVerify || undefined }; }
function reset(): void { const item = props.mapping; const currentZoneName = props.zones.find((zone) => zone.id === item?.zoneId)?.name || item?.zoneName || ""; const escapedZone = currentZoneName.replace(/[.*+?^${}()|[\]\\]/g, "\\$&"); draft.zoneId = item?.zoneId || props.defaultZoneId || props.zones[0]?.id || ""; draft.subdomain = item?.hostname === currentZoneName ? "@" : currentZoneName ? item?.hostname.replace(new RegExp(`\\.${escapedZone}$`), "") || "@" : item?.hostname || "@"; draft.path = item?.path || ""; draft.targetType = item?.targetType || "host"; draft.protocol = item?.protocol || "http"; draft.targetHost = item?.targetType === "lan" ? item.targetHost : ""; draft.targetPort = item ? String(item.targetPort) : ""; draft.enabled = item?.enabled ?? true; draft.noTLSVerify = item?.noTLSVerify ?? false; Object.keys(errors).forEach((key) => delete errors[key]); }
function validate(): boolean { Object.keys(errors).forEach((key) => delete errors[key]); if (!draft.zoneId || !zoneName.value) errors.zone = "请选择一个可用 Zone。"; if (!draft.subdomain.trim() || !(draft.subdomain === "@" || /^(?:\*\.)?[a-z0-9](?:[a-z0-9.-]*[a-z0-9])?$/i.test(draft.subdomain) || draft.subdomain === "*")) errors.subdomain = "请输入有效的子域名、@ 或左侧通配符。"; const port = Number(draft.targetPort); if (!Number.isInteger(port) || port < 1 || port > 65535) errors.port = "端口必须在 1 至 65535 之间。"; if (draft.targetType === "lan" && !draft.targetHost.trim()) errors.host = "请输入局域网 IP 或 hostname。"; return !Object.keys(errors).length; }
function action(kind: "save"|"test"): void {
  if (!validate()) {
    void nextTick(() => form.value?.querySelector<HTMLElement>("[aria-invalid=true]")?.focus());
    return;
  }
  const input = payload();
  if (kind === "save") emit("save", input);
  else emit("test", input);
}
function close(): void { if (!props.saving && !props.testing) emit("close"); }
function keydown(event: KeyboardEvent): void { if (event.key === "Escape") { event.preventDefault(); close(); return; } if (event.key !== "Tab" || !panel.value) return; const items = [...panel.value.querySelectorAll<HTMLElement>('button:not([disabled]),input:not([disabled]),[tabindex]:not([tabindex="-1"])')]; const first = items[0], last = items.at(-1); if (!first || !last) return; if (event.shiftKey && document.activeElement === first) { event.preventDefault(); last.focus(); } else if (!event.shiftKey && document.activeElement === last) { event.preventDefault(); first.focus(); } }
watch(() => props.open, async (open) => { if (open) { reset(); previous = document.activeElement as HTMLElement | null; setLocked(true); document.addEventListener("keydown", keydown); await nextTick(); panel.value?.querySelector<HTMLElement>("input")?.focus(); } else { setLocked(false); document.removeEventListener("keydown", keydown); previous?.focus(); } });
watch(() => props.mapping, reset); watch(() => props.zones, () => { if (props.open) reset(); }); onBeforeUnmount(() => document.removeEventListener("keydown", keydown));
</script>

<template>
  <Teleport to="body"><Transition name="drawer"><div v-if="open" class="fixed inset-0 z-[70]"><div class="absolute inset-0 bg-black/25 backdrop-blur-[1px]" @click="close"/><aside ref="panel" class="drawer-panel absolute inset-y-0 right-0 flex w-full max-w-[520px] flex-col bg-white shadow-[-16px_0_50px_rgba(17,24,39,.13)]" role="dialog" aria-modal="true" aria-labelledby="mapping-title"><header class="flex min-h-[68px] items-center justify-between border-b border-black/[.08] px-5"><div><h2 id="mapping-title" class="text-[15px] font-semibold">{{ mapping ? "编辑映射" : "添加映射" }}</h2><p class="mt-1 text-[11px] text-muted">Ingress 与 DNS 将自动配置</p></div><button class="icon-btn" type="button" aria-label="关闭抽屉" @click="close">×</button></header>
    <form ref="form" class="flex-1 overflow-y-auto p-5" novalidate @submit.prevent="action('save')"><p class="eyebrow">公网地址</p><div class="mt-3"><label class="label">Cloudflare Zone</label><SelectMenu v-model="draft.zoneId" :options="zoneOptions" :disabled="zonesLoading" searchable search-placeholder="搜索 Zone" aria-label="Cloudflare Zone"/><p v-if="zonesLoading" class="mt-1.5 flex items-center gap-2 text-[11px] text-muted"><span class="spinner"/>正在加载可用 Zone</p><p v-else-if="errors.zone" class="mt-1 text-[11px] text-red-600">{{ errors.zone }}</p></div><div class="mt-4 grid grid-cols-[minmax(0,1fr)_auto] items-start gap-2"><div><label class="label" for="subdomain">子域名</label><input id="subdomain" v-model.trim="draft.subdomain" class="field" :aria-invalid="!!errors.subdomain" placeholder="app、@ 或 *"><p v-if="errors.subdomain" class="mt-1 text-[11px] text-red-600">{{ errors.subdomain }}</p></div><div v-if="draft.subdomain !== '@'" class="max-w-48 truncate pt-7 text-xs text-muted">.{{ zoneName }}</div></div><p class="mt-2 truncate rounded-md bg-black/[.03] px-3 py-2 font-mono text-[11px]">https://{{ hostname }}{{ draft.path }}</p><label class="label mt-4" for="path">Path（可选）</label><input id="path" v-model="draft.path" class="field font-mono" placeholder="^/api/.*">
    <p class="eyebrow mt-6">目标服务</p><div class="mt-3 grid grid-cols-2 gap-3"><div><label class="label">目标类型</label><SelectMenu v-model="draft.targetType" :options="[{value:'host',label:'当前宿主机'},{value:'lan',label:'局域网设备'}]"/></div><div><label class="label">协议</label><SelectMenu v-model="draft.protocol" :options="[{value:'http',label:'HTTP'},{value:'https',label:'HTTPS'}]"/></div></div><div class="mt-4 grid grid-cols-[minmax(0,1fr)_110px] gap-3"><div><label class="label" for="target-host">目标地址</label><input id="target-host" v-model="draft.targetHost" class="field" :disabled="draft.targetType === 'host'" :placeholder="draft.targetType === 'host' ? '127.0.0.1' : '192.168.1.20'" :aria-invalid="!!errors.host"><p v-if="errors.host" class="mt-1 text-[11px] text-red-600">{{ errors.host }}</p></div><div><label class="label" for="target-port">端口</label><input id="target-port" v-model="draft.targetPort" class="field" type="number" min="1" max="65535" :aria-invalid="!!errors.port"><p v-if="errors.port" class="mt-1 text-[11px] text-red-600">{{ errors.port }}</p></div></div>
    <label v-if="draft.protocol === 'https'" class="mt-5 flex items-center gap-2 rounded-lg border border-black/[.08] bg-black/[.02] p-3 text-xs"><input v-model="draft.noTLSVerify" type="checkbox">不验证内网 HTTPS 证书</label>
    <div v-if="testing || testResult" class="mt-4 rounded-lg border border-black/[.08] bg-black/[.02] p-3 text-xs"><p class="font-medium">连通性测试</p><p class="mt-1 text-muted"><span v-if="testing" class="spinner mr-2 inline-block align-middle"/>{{ testing ? "正在执行 TCP、HTTP/TLS 检查..." : testResult?.ok ? `Origin 已响应 · ${testResult.durationMs} ms${testResult.status ? ` · HTTP ${testResult.status}` : ''}` : testResult?.message || testResult?.category }}</p></div><div v-if="saving" class="mt-4 rounded-lg border border-primary/15 bg-primary/[.035] p-3" role="status" aria-live="polite"><p class="flex items-center gap-2 text-xs font-medium"><span class="spinner"/>正在应用 Cloudflare 配置</p><p class="mt-2 text-[11px] text-muted">{{ displayStage }}<template v-if="operation"> · {{ operation.status }}</template></p><div class="mt-3 h-1 overflow-hidden rounded-full bg-primary/10"><span class="stage-progress block h-full w-1/3 rounded-full bg-primary"/></div></div><p v-if="serverError" class="alert-error mt-4" role="alert">{{ serverError }}</p></form>
    <footer class="flex flex-wrap justify-end gap-2 border-t border-black/[.08] px-5 py-3.5"><button class="btn-secondary mr-auto" type="button" :disabled="saving || testing" @click="action('test')"><span v-if="testing" class="spinner"/>{{ testing ? "测试中" : "测试目标" }}</button><button class="btn-secondary" type="button" :disabled="saving || testing" @click="close">取消</button><button class="btn-primary min-w-24" type="button" :disabled="saving || testing" @click="action('save')"><span v-if="saving" class="spinner"/>{{ saving ? "正在配置" : mapping ? "保存更改" : "创建映射" }}</button></footer></aside></div></Transition></Teleport>
</template>

<style scoped>.drawer-enter-active .drawer-panel,.drawer-leave-active .drawer-panel{transition:transform 280ms var(--ease-out)}.drawer-enter-from .drawer-panel,.drawer-leave-to .drawer-panel{transform:translateX(100%)}.stage-progress{animation:stage-slide 1.2s ease-in-out infinite}@keyframes stage-slide{0%{transform:translateX(-100%)}100%{transform:translateX(300%)}}@media(max-width:520px){.drawer-panel{inset:6vh 0 0;max-width:none;border-radius:14px 14px 0 0}.drawer-enter-from .drawer-panel,.drawer-leave-to .drawer-panel{transform:translateY(100%)}}</style>
