<script setup lang="ts">
import { computed, nextTick, onBeforeUnmount, onMounted, ref, watch } from "vue";
const props = withDefaults(defineProps<{ modelValue: string; options: { value: string; label: string }[]; ariaLabel?: string; disabled?: boolean; searchable?: boolean; searchPlaceholder?: string }>(), { disabled: false, searchable: false, searchPlaceholder: "搜索..." });
const emit = defineEmits<{ "update:modelValue": [value: string] }>();
const root = ref<HTMLElement | null>(null); const open = ref(false);
const search = ref("");
const selected = computed(() => props.options.find((item) => item.value === props.modelValue)?.label || "请选择");
const filtered = computed(() => { const needle = search.value.trim().toLowerCase(); return needle ? props.options.filter((item) => item.label.toLowerCase().includes(needle)) : props.options; });
function choose(value: string) { emit("update:modelValue", value); open.value = false; root.value?.querySelector<HTMLButtonElement>("button")?.focus(); }
function outside(event: MouseEvent) { if (!root.value?.contains(event.target as Node)) open.value = false; }
async function keydown(event: KeyboardEvent) { if (event.key === "Escape") { open.value = false; root.value?.querySelector<HTMLButtonElement>("button")?.focus(); } if (event.key === "ArrowDown" && !open.value) { event.preventDefault(); open.value = true; await nextTick(); root.value?.querySelector<HTMLButtonElement>("[role=option]")?.focus(); } }
watch(open, async (value) => { if (!value) { search.value = ""; return; } if (props.searchable) { await nextTick(); root.value?.querySelector<HTMLInputElement>("input[type=search]")?.focus(); } });
onMounted(() => document.addEventListener("click", outside)); onBeforeUnmount(() => document.removeEventListener("click", outside));
</script>
<template><div ref="root" class="relative" @keydown="keydown"><button class="field flex items-center justify-between gap-3 text-left" type="button" :disabled="disabled" :aria-label="ariaLabel" :aria-expanded="open" aria-haspopup="listbox" @click="open = !open"><span class="truncate">{{ selected }}</span><span aria-hidden="true">⌄</span></button><Transition name="select"><div v-if="open" class="absolute z-30 mt-1.5 w-full min-w-40 rounded-lg border border-black/[.1] bg-white p-1 shadow-[0_12px_32px_rgba(0,0,0,.12)]" role="listbox"><div v-if="searchable" class="border-b border-black/[.07] p-1 pb-2"><input v-model="search" class="field !h-8" type="search" :placeholder="searchPlaceholder" :aria-label="searchPlaceholder" @keydown.stop></div><div class="max-h-52 overflow-auto pt-1"><button v-for="option in filtered" :key="option.value" class="flex w-full items-center justify-between rounded-md px-2.5 py-2 text-left text-xs text-muted hover:bg-black/[.05] hover:text-[#1c1f23]" :class="option.value === modelValue ? 'bg-black/[.045] !text-[#1c1f23]' : ''" type="button" role="option" :aria-selected="option.value === modelValue" @click="choose(option.value)">{{ option.label }}<span v-if="option.value === modelValue" class="text-primary">✓</span></button><p v-if="!filtered.length" class="px-2.5 py-3 text-center text-xs text-muted">没有匹配项</p></div></div></Transition></div></template>
