<script setup lang="ts">
import { computed, nextTick, onBeforeUnmount, onMounted, ref } from "vue";
import { apiClient } from "../api";
import { messageFor, useAppState } from "../state";
import type { ConnectorLog, ConnectorSnapshot } from "../types";
import StatusBadge from "../components/StatusBadge.vue";

const { state, setConnector, notify } = useAppState();
const logs = ref<ConnectorLog[]>([]); const loadingLogs = ref(true); const actionBusy = ref<"start"|"stop"|null>(null); const restarting = ref(false); const waitingHealthy = ref(false); const connected = ref(false); const follow = ref(true); const logPanel = ref<HTMLElement | null>(null);
let source: EventSource | null = null; let restartTimeout: number | undefined;
const connector = computed(() => state.connector); const restartLabel = computed(() => restarting.value ? waitingHealthy.value ? "等待 Connector 运行" : "正在重启" : "重启 Connector");

async function scrollEnd(): Promise<void> { if (!follow.value) return; await nextTick(); if (logPanel.value) logPanel.value.scrollTop = logPanel.value.scrollHeight; }
function addLog(log: ConnectorLog): void { if (logs.value.some((item) => item.id === log.id)) return; logs.value.push(log); if (logs.value.length > 1000) logs.value.splice(0, logs.value.length - 1000); void scrollEnd(); }
function statusEvent(event: MessageEvent<string>): void { const snapshot = JSON.parse(event.data) as ConnectorSnapshot; setConnector(snapshot); if (restarting.value && snapshot.state === "running") { restarting.value = false; waitingHealthy.value = false; if (restartTimeout) clearTimeout(restartTimeout); notify("Connector 已恢复运行", "success"); } else if (restarting.value) waitingHealthy.value = true; }
function connectEvents(): void { source?.close(); source = new EventSource("/api/connector/events"); source.addEventListener("open", () => connected.value = true); source.addEventListener("error", () => connected.value = false); source.addEventListener("status", (event) => statusEvent(event as MessageEvent<string>)); source.addEventListener("log", (event) => addLog(JSON.parse((event as MessageEvent<string>).data) as ConnectorLog)); }
async function load(): Promise<void> { loadingLogs.value = true; try { const [snapshot, recent] = await Promise.all([apiClient.connector(), apiClient.connectorLogs(500)]); setConnector(snapshot); logs.value = recent; await scrollEnd(); } catch (error) { notify(messageFor(error), "error"); } finally { loadingLogs.value = false; } }
async function action(value: "start"|"stop"): Promise<void> { actionBusy.value = value; try { setConnector(await apiClient.connectorAction(value)); notify(value === "start" ? "Connector 启动命令已发送" : "Connector 已停止", "success"); } catch (error) { notify(messageFor(error), "error"); } finally { actionBusy.value = null; } }
async function restart(): Promise<void> { restarting.value = true; waitingHealthy.value = false; try { const snapshot = await apiClient.connectorAction("restart"); setConnector(snapshot); waitingHealthy.value = snapshot.state !== "running"; if (snapshot.state === "running") { restarting.value = false; notify("Connector 已重启", "success"); } else restartTimeout = window.setTimeout(() => { restarting.value = false; waitingHealthy.value = false; notify("等待 Connector 运行超时，请检查日志", "error"); }, 30_000); } catch (error) { restarting.value = false; notify(messageFor(error), "error"); } }
function clearLogs(): void { logs.value = []; }
onMounted(async () => { await load(); connectEvents(); }); onBeforeUnmount(() => { source?.close(); if (restartTimeout) clearTimeout(restartTimeout); });
</script>

<template>
  <section><header class="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p class="eyebrow">运行时</p><h1 class="mt-2 text-2xl font-semibold tracking-[-.035em]">Connector</h1><p class="mt-2 text-[13px] text-muted">管理 cloudflared 子进程并查看实时输出。</p></div><div class="flex flex-wrap gap-2"><button v-if="connector?.state !== 'running'" class="btn-primary" :disabled="!!actionBusy || restarting" @click="action('start')"><span v-if="actionBusy==='start'" class="spinner"/>启动</button><button v-else class="btn-secondary" :disabled="!!actionBusy || restarting" @click="action('stop')"><span v-if="actionBusy==='stop'" class="spinner"/>停止</button><button class="btn-secondary min-w-32" :disabled="!!actionBusy || restarting" @click="restart"><span v-if="restarting" class="spinner"/>{{ restartLabel }}</button></div></header>
    <section class="mt-7 grid grid-cols-2 gap-3 lg:grid-cols-4"><article class="card p-4"><p class="text-[11px] text-muted">进程状态</p><div class="mt-3"><StatusBadge :status="connector?.state || 'unknown'"/></div></article><article class="card p-4"><p class="text-[11px] text-muted">PID</p><p class="mt-2 font-mono text-xl font-semibold">{{ connector?.pid ?? '—' }}</p></article><article class="card p-4"><p class="text-[11px] text-muted">自动运行</p><p class="mt-2 text-sm font-medium">{{ connector?.desired ? '已启用' : '已停用' }}</p></article><article class="card p-4"><p class="text-[11px] text-muted">日志通道</p><p class="mt-2 flex items-center gap-2 text-sm font-medium"><span class="h-1.5 w-1.5 rounded-full" :class="connected?'bg-emerald-500':'bg-red-500'"/>{{ connected ? 'SSE 已连接' : '正在重连' }}</p></article></section>
    <section class="card mt-5 overflow-hidden"><header class="flex flex-wrap items-center gap-3 border-b border-black/[.08] px-4 py-3"><div><h2 class="text-sm font-medium">实时日志</h2><p class="mt-1 text-[10px] text-muted">最近 {{ logs.length }} 条，Token 已由后端脱敏</p></div><label class="ml-auto flex items-center gap-2 text-[11px] text-muted"><input v-model="follow" type="checkbox">自动滚动</label><button class="btn-ghost !h-8" @click="clearLogs">清空视图</button></header><div ref="logPanel" class="h-[min(58vh,560px)] overflow-auto bg-[#17191d] p-4 font-mono text-[11px] leading-5 text-[#c9cdd4]" role="log" aria-live="polite"><div v-if="loadingLogs" class="grid h-full place-items-center text-muted"><span class="flex items-center gap-2"><span class="spinner"/>正在加载日志</span></div><p v-for="log in logs" v-else :key="log.id" class="flex gap-3 border-b border-white/[.025] py-0.5"><time class="shrink-0 text-[#717782]">{{ new Date(log.timestamp).toLocaleTimeString('zh-CN',{hour12:false}) }}</time><span class="w-12 shrink-0" :class="log.stream==='stderr'?'text-red-400':log.stream==='system'?'text-indigo-300':'text-emerald-300'">{{ log.stream }}</span><span class="whitespace-pre-wrap break-all">{{ log.message }}</span></p><p v-if="!loadingLogs&&!logs.length" class="grid h-full place-items-center text-[#717782]">暂无 Connector 日志</p></div></section>
  </section>
</template>
